### ISSUE TITLE
Question About the memory bank

### ISSUE THREAD

**Issue by Gary-code** [yl3800/IGV#4]
loading time is too long ?

**Comment by yl3800** [comment]
You can modify the memory bank as in batch memory bank to avoid load memory bank, that is, the sample the complement scene from the current batch instead of the whole training set. I tried that, it will not hurt the performance.

**Comment by Gary-code** [comment]
thanks a lot. I have successfully run the code

**Comment by zongzhao23** [comment]
> thanks a lot. I have successfully run the code

Hi bro, is it convenient for you to share the pre-computed features for MSVD with me? The link in this github has expired and the author seems busy. Thanks in advance!
