### ISSUE TITLE
Pre-computed feature for MSVD and MSRVTT

### ISSUE THREAD

**Issue by zongzhao23** [yl3800/IGV#6]
Nice work! Can you provide the link to pre-computed feature for MSVD and MSRVTT? The link you provided for MSVD has expired.

**Comment by Gary-code** [comment]
Hi, I did not use the features the repo provide. For NExT-QA I use the officially provided video feature, for MSRVTT and MSVD please refer [here](https://github.com/thaolmk54/hcrn-videoqa/tree/master/preprocess). Simply, I just use a I3D network to extract the video features into 2048 dimensions.

**Comment by zongzhao23** [comment]
> 
Thanks for your reply! How about the textual features? I noticed that the author uses the bert features but HCRN uses the glove features. What's more, can you reproduce the results in the NExT-QA dataset for 51.34? My model's performance is much lower than it.

**Comment by yl3800** [comment]
feature updated
